### PR TITLE
fix Fix the link on the Mac platform OpenCL method

### PR DESCRIPTION
**Pull request by tqcq**

### CODE REVIEW

**Comment by LostRuins** [comment]
Hi, anyone else can verify that this change is necessary for OSX? 

I don't use a mac so I cannot tell. I thought it was compiling fine previously? Why is this required?

**Comment by tqcq** [comment]
You can refer to this code 
https://github.com/ggerganov/llama.cpp/blob/master/Makefile#L181

**Comment by beebopkim** [comment]
In my computer, the change of Makefile produced an error related with ld. I have a Mac Studio with M1 Max and my macOS version is ventura 13.4. I guess I need more changes in Makefile to look up clblast header and library files.

koboldcpp_LLAMA_CLBLAST-1

**Comment by tqcq** [comment]
> In my computer, the change of Makefile produced an error related with ld. I have a Mac Studio with M1 Max and my macOS version is ventura 13.4. I guess I need more changes in Makefile to look up clblast header and library files.
> 
> koboldcpp_LLAMA_CLBLAST-1

I'm not sure if clblast is already installed on your computer, maybe you can try to install clblast, eg brew install clblast.

**Comment by tqcq** [comment]
> > > In my computer, the change of Makefile produced an error related with ld. I have a Mac Studio with M1 Max and my macOS version is ventura 13.4. I guess I need more changes in Makefile to look up clblast header and library files.
> > > koboldcpp_LLAMA_CLBLAST-1
> > 
> > 
> > I'm not sure if clblast is already installed on your computer, maybe you can try to install clblast, eg `brew install clblast`.
> 
> Screenshot 2023-06-13 at 12 12 45 AM
> Of course I installed clblast in Homebrew environment.

Thanks for the information, it seems that clblast is not in the default search directory of the compiler, trying to tell the compiler that your library is in a non-standard directory through an environment variable may solve this problem.
```bash
## brew link clblast

export LDFLAGS= -L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/openblas/lib -L/opt/homebrew/opt/clblast/lib
export CXXFLAGS= -I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/openblas/include -I/opt/homebrew/opt/clblast/include
export CPLUS_INCLUDE_PATH=:/opt/homebrew/opt/clblast/include:/opt/homebrew/opt/openblas/include
export C_INCLUDE_PATH=::/opt/homebrew/opt/clblast/include:/opt/homebrew/opt/openblas/include

# your make command
```

**Comment by LostRuins** [comment]
@tqcq can I check if it builds successfully without -framework flag? 
If it is still working, I think it's better to maintain wider compatibility

**Comment by tqcq** [comment]
> 
Since I'm not good at English, I don't quite understand what you mean, I guess maybe you want to see the difference between using -l and -framework
截屏2023-06-13 21 34 46

**Comment by tqcq** [comment]
@LostRuins 
If you want to test on different mac environments, there is a solution for deploying various versions of Mac through Docker. https://github.com/sickcodes/Docker-OSX
Unfortunately, my network cannot download this image.
preview for Docker-OSX

**Comment by LostRuins** [comment]
Anyone else can comment? Because seems like some others cannot use this flag

**Comment by beebopkim** [comment]
> Anyone else can comment? Because seems like some others cannot use this flag

@LostRuins For x86_64 and arm64 on macOS (or older Mac OS X), ```-framework``` is inevitable because Apple designed it this way. If there is another way, it must be using a compiler not coming with Xcode made by Apple.

**Comment by LostRuins** [comment]
Got it. If there are no other objections, i will merge this.

**Comment by beebopkim** [comment]
> Unfortunately, my network cannot download this image.
> preview for Docker-OSX

Now I understand why you do this. For Intel Macs, CLBlast definitely helps gaining inference speed.

For My M1 Max, build was okay but execution was failed. It looks like that ```CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE``` property for ```clCreateCommandQueue``` is not supported on M1 Max.

**Comment by beebopkim** [comment]
> For My M1 Max, build was okay but execution was failed. It looks like that `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE` property for `clCreateCommandQueue` is not supported on M1 Max.

@LostRuins I think it is okay to merge this because ```CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE``` problem, there is no way to avoid or detour on M1(made M2 too). On Apple Silicon, OpenGL, OpenCL is deprecated, and Apple puts some limitations like no FP16. I guess *no ```CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE```*  is one of them.

But this commit is helpful for older macOS(or Mac OS X) users, I see this is good to be merge.

**Comment by beebopkim** [comment]
> > > Unfortunately, my network cannot download this image.
> > > preview for Docker-OSX
> > 
> > 
> > Now I understand why you do this. For Intel Macs, CLBlast definitely helps gaining inference speed.
> > For My M1 Max, build was okay but execution was failed. It looks like that `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE` property for `clCreateCommandQueue` is not supported on M1 Max.
> 
> My computer is M1 Max, I'm curious what's wrong with your computer, maybe I can take a look, although I'm not familiar with clblast ,but it does improve speed. Below is a picture of me loading `koboldcpp_clblast.so`. 截屏2023-06-13 22 43 14

Why don't use Metal inference? It is the fastest way I've ever seen on my M1 Max.

**Comment by tqcq** [comment]
> > > > Unfortunately, my network cannot download this image.
> > > > preview for Docker-OSX
> > > 
> > > 
> > > Now I understand why you do this. For Intel Macs, CLBlast definitely helps gaining inference speed.
> > > For My M1 Max, build was okay but execution was failed. It looks like that `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE` property for `clCreateCommandQueue` is not supported on M1 Max.
> > 
> > 
> > My computer is M1 Max, I'm curious what's wrong with your computer, maybe I can take a look, although I'm not familiar with clblast ,but it does improve speed. Below is a picture of me loading `koboldcpp_clblast.so`. 截屏2023-06-13 22 43 14
> 
> Why don't use Metal inference? It is the fastest way I've ever seen on my M1 Max.

Thanks for the reminder, I didn't know Metal had arrived, I'll give it a try.

**Comment by tqcq** [comment]
@beebopkim I get a error.
Generating (1 / 80 tokens)GGML_ASSERT: ggml-metal.m:678: false && "not implemented"
https://github.com/LostRuins/koboldcpp/blob/fb67506c1b49a0fdc902454b8b10c8a0c31add26/ggml-metal.m#L644-L650
Looks like Metal doesn't support Q_8 yet.

**Comment by beebopkim** [comment]
> @beebopkim I get a error. Generating (1 / 80 tokens)GGML_ASSERT: ggml-metal.m:678: false && "not implemented"
> 
> https://github.com/LostRuins/koboldcpp/blob/fb67506c1b49a0fdc902454b8b10c8a0c31add26/ggml-metal.m#L644-L650
> 
> 
> Looks like Metal doesn't support Q_8 yet.
> But as you said, it's really fast on other types.

Metal inference is supported for q4_0, q4_1, q2_k, q3_k, q4_k, q5_k, and q6_k on latest commit. llama.cpp also support Metal inference for f16.

**Comment by tqcq** [comment]
> > @beebopkim I get a error. Generating (1 / 80 tokens)GGML_ASSERT: ggml-metal.m:678: false && "not implemented"
> > https://github.com/LostRuins/koboldcpp/blob/fb67506c1b49a0fdc902454b8b10c8a0c31add26/ggml-metal.m#L644-L650
> > 
> > Looks like Metal doesn't support Q_8 yet.
> > But as you said, it's really fast on other types.
> 
> Metal inference is supported for q4_0, q4_1, q2_k, q3_k, q4_k, q5_k, and q6_k on latest commit. llama.cpp also supports Metal inference for f16.

May I ask which of the 30B series models you have tried is the best, I have always used the WizardLM-30B-Uncensored, but occasionally have some minor issues. I think maybe you have a better answer.

> > @beebopkim I get a error. Generating (1 / 80 tokens)GGML_ASSERT: ggml-metal.m:678: false && "not implemented"
> > https://github.com/LostRuins/koboldcpp/blob/fb67506c1b49a0fdc902454b8b10c8a0c31add26/ggml-metal.m#L644-L650
> > 
> > Looks like Metal doesn't support Q_8 yet.
> > But as you said, it's really fast on other types.
> 
> Metal inference is supported for q4_0, q4_1, q2_k, q3_k, q4_k, q5_k, and q6_k on latest commit. llama.cpp also supports Metal inference for f16.

Great, I'm converting WizardLM-30B-Uncensored to Q4_0.
May I ask which of the 30B series models you have tried is the best, I have always used the WizardLM-30B-Uncensored, but occasionally have some minor issues. I think maybe you have a better answer.

**Comment by beebopkim** [comment]
> Great, I'm converting WizardLM-30B-Uncensored to Q4_0. May I ask which of the 30B series models you have tried is the best, I have always used the WizardLM-30B-Uncensored, but occasionally have some minor issues. I think maybe you have a better answer.

@tqcq For 30B, I have only 1 model other than LLaMa, and it is WizardLM-30B-Uncensored. There are not so many model 30B and above, so I think many people would recommend WizardLM-30B-Uncensored.

**Comment by LostRuins** [comment]
merged as recommended, please let me know if anything breaks

**Pull request merged**
