### PR TITLE
Readme - Instructions of how to compile with a custom or newer version of the libraries of lib folder at Windows.

### PR DESCRIPTION
**Pull request by gustrd**
I tested it and worked ok.

### CODE REVIEW

**Comment by gustrd** [comment]
@Midaychi, I remember you wished to do it, could you test also?

**Comment by Midaychi** [comment]
Pulled your repo.
Got clean w64 kit

put binary for cmake in there
put precompiled boost libs in there 
added to path
powershell-> followed instructions for compiling opencl-sdk, had to modify the instruction that pointed cmake to the vcpkg.cmake
moved OpenCl.dll to -> OpenCL.lib in the koboldcpp branch's lib folder
powershell -> compiled openblas,
 moved libopenblas.dll -> koboldcpp libopenblas.lib in lib folder

Had visual studio 17 2022 already set up for c++, cl.h was fairly easy to get, cmake was obsessed with using my cuda conpute 11.7 toolkit's cl.h no matter what I changed so I gave up and let it

Release build, -> moved to koboldcpp lib as clblast.lib

closed powershell, opened w64 kit's console specifically now
"make" in kobodcpp folder
"make_pyinstaller.bat" in koboldcpp folder

ran the exe in dists with  --smartcontext --psutil_set_threads --blasbatchsize 1024 --useclblast 0 0

seems to work at least with the vicuna 4bit 1.1 7b I had it load?

**Comment by Midaychi** [comment]
On a side note, I think I basically doubled my token generation rate.

**Comment by LostRuins** [comment]
@gustrd For libopenblas I compiled it from source from the xianyi/OpenBLAS github repo, which was at v0.3.22 at that time. For CLBlast, I used the prebuilt binaries provided by CNugteren/CLBlast github repo, at version 1.5.3

@Midaychi that is interesting, that it would be twice as fast - do you mean for the prompt processing or for the text generation? Is it that much faster compared versus the provided executables? If you are willing to share your build, I'd be glad to try it out to compare - it's possible that I may be doing something wrong

**Comment by Midaychi** [comment]
I mean that the last time I tested I was getting maybe a token every 300 ms on llama vicuña 7b 1.1 4.0 quant on a fairly decent 12th Gen Intel cpu, but I tested this build and I was generating multiple tokens a decent but faster, maybe one every 150 ms?
Couk easily have just been a code change between then and now, or using one of the libraries compiled with processor-specific tuning (almost all steps I compiled auto-picked tuned flags).
Either way, I would prefer not to swap precompiled binaries, and your processor and arch would probably be different enougb to cause errors on init anyways.

**Comment by gustrd** [comment]
> @gustrd For libopenblas I compiled it from source from the xianyi/OpenBLAS github repo, which was at v0.3.22 at that time. For CLBlast, I used the prebuilt binaries provided by CNugteren/CLBlast github repo, at version 1.5.3
> 
> @Midaychi that is interesting, that it would be twice as fast - do you mean for the prompt processing or for the text generation? Is it that much faster compared versus the provided executables? If you are willing to share your build, I'd be glad to try it out to compare - it's possible that I may be doing something wrong

And for OpenCL? I had a hard time to find a good source.

**Comment by Midaychi** [comment]
> > @gustrd For libopenblas I compiled it from source from the xianyi/OpenBLAS github repo, which was at v0.3.22 at that time. For CLBlast, I used the prebuilt binaries provided by CNugteren/CLBlast github repo, at version 1.5.3
> > 
> > @Midaychi that is interesting, that it would be twice as fast - do you mean for the prompt processing or for the text generation? Is it that much faster compared versus the provided executables? If you are willing to share your build, I'd be glad to try it out to compare - it's possible that I may be doing something wrong
> 
> And for OpenCL? I had a hard time to find a good source.

Kronos group's opencl-sdk. Compiling that results in their sdk including an opencl.dll binary. That repo also has cl.h headers for clblast compiling.if you don't have the cuda framework.

**Comment by gustrd** [comment]
> I mean that the last time I tested I was getting maybe a token every 300 ms on llama vicuña 7b 1.1 4.0 quant on a fairly decent 12th Gen Intel cpu, but I tested this build and I was generating multiple tokens a decent but faster, maybe one every 150 ms? Couk easily have just been a code change between then and now, or using one of the libraries compiled with processor-specific tuning (almost all steps I compiled auto-picked tuned flags). Either way, I would prefer not to swap precompiled binaries, and your processor and arch would probably be different enougb to cause errors on init anyways.

@Midaychi , @LostRuins 

I tried this compiling everything at my machine (OpenCL, OpenBlas, CLBlast and KoboldCpp). I hoped to have a performance gain, but I had none at a i5-8th processor:

	Concedo 1.10 clblast - 		test 1: 112,2s
					                test 2: 116,2s
					                test 3: 116,5s
				
	GRD_compiled 1.10 clblast - 	test 1: 116,9s
					                test 2: 117,3s
					                test 3: 116,9s
					           
The tests were all done with the same context at Instruct mode, restart the program everytime to avoid context reuse.

Are you still able to reproduce this @Midaychi ? If true I will try it at my i7-12th.

**Comment by Midaychi** [comment]
> > I mean that the last time I tested I was getting maybe a token every 300 ms on llama vicuña 7b 1.1 4.0 quant on a fairly decent 12th Gen Intel cpu, but I tested this build and I was generating multiple tokens a decent but faster, maybe one every 150 ms? Couk easily have just been a code change between then and now, or using one of the libraries compiled with processor-specific tuning (almost all steps I compiled auto-picked tuned flags). Either way, I would prefer not to swap precompiled binaries, and your processor and arch would probably be different enougb to cause errors on init anyways.
> 
> @Midaychi , @LostRuins 
> 
> I tried this compiling everything at my machine (OpenCL, OpenBlas, CLBlast and KoboldCpp). I hoped to have a performance gain, but I had none at a i5-8th processor:
> 
> 	Concedo 1.10 clblast - 		test 1: 112,2s
> 					                test 2: 116,2s
> 					                test 3: 116,5s
> 				
> 	GRD_compiled 1.10 clblast - 	test 1: 116,9s
> 					                test 2: 117,3s
> 					                test 3: 116,9s
> 					           
> The tests were all done with the same context at Instruct mode, restart the program everytime to avoid context reuse.
> 
> Are you still able to reproduce this @Midaychi ? If true I will try it at my i7-12th.
> 					

I don't really have any recorded metrics to prove I'm not making things up or just coincidentally decided to test on a day of a code refactoring. So I wouldn't fuss over it if you are asking.

**Pull request merged**
