### PR TITLE
Update CMakeLists.txt to C/C++ 17

### PR DESCRIPTION
**Pull request by askmyteapot**
Upstream has changed to C/C++ 17 and now is required to get KoboldCPP to build.

### CODE REVIEW

**Comment by askmyteapot** [comment]
Build error before change
```
 ggml-cpu-traits.cpp
C:\koboldcpp\ggml\src\ggml-cpu\ggml-cpu-traits.h(18,21): error C2429: language feature 'nested-namespace-definition' re
quires compiler flag '/std:c++17' [C:\koboldcpp\build\ggml.vcxproj]
  (compiling source file '../ggml/src/ggml-cpu/ggml-cpu-traits.cpp')

C:\koboldcpp\ggml\src\ggml-cpu\ggml-cpu-traits.cpp(6,21): error C2429: language feature 'nested-namespace-definition' r
equires compiler flag '/std:c++17' [C:\koboldcpp\build\ggml.vcxproj]
  ggml-threading.cpp
  ggml-cpu-aarch64.cpp
C:\koboldcpp\ggml\src\ggml-cpu\ggml-cpu-traits.h(18,21): error C2429: language feature 'nested-namespace-definition' re
quires compiler flag '/std:c++17' [C:\koboldcpp\build\ggml.vcxproj]
  (compiling source file '../ggml/src/ggml-cpu/ggml-cpu-aarch64.cpp')

C:\koboldcpp\ggml\src\ggml-cpu\ggml-cpu-aarch64.cpp(3824,30): error C2429: language feature 'nested-namespace-definitio
n' requires compiler flag '/std:c++17' [C:\koboldcpp\build\ggml.vcxproj]
C:\koboldcpp\ggml\src\ggml-cpu\ggml-cpu-aarch64.cpp(4213,30): error C2429: language feature 'nested-namespace-definitio
n' requires compiler flag '/std:c++17' [C:\koboldcpp\build\ggml.vcxproj]
```

**Comment by askmyteapot** [comment]
I included an update to the makefile. I'm not 100% sure its needed, as when i do a `make -j 16` it built ok. But thats in a windows environment with w64devkit. 

I havent tested on linux

**Comment by LostRuins** [comment]
Thanks for bringing this to my attention! I thought I caught all the C++17 issues, but apparently I missed one.

For now, I'd prefer avoiding C++17 as it's too new. Instead, can you try pulling and building the latest commit?

**Comment by askmyteapot** [comment]
> Thanks for bringing this to my attention! I thought I caught all the C++17 issues, but apparently I missed one.
> 
> For now, I'd prefer avoiding C++17 as it's too new. Instead, can you try pulling and building the latest commit?

New commit works.  Can close this. (pending discord war outcome :P)

**Comment by LostRuins** [comment]
Thanks! i'll close it first, but if i ever do need to upgrade i'll refer back to it. Appreciate the effort anyway

**Comment by LostRuins** [comment]
oops too many conflicts

**Pull request closed without merging**
