### PR TITLE
CUDA 12 CI

### PR DESCRIPTION
**Pull request by henk717**
This PR does a couple of changes, including one minor breaking change.
- Koboldcpp.sh is now compatible with different CUDA versions that can be specified with the KCPP_CUDA env var (Version needs to be an existing one on conda's repo)
- Koboldcpp.sh now allows appending something to the file name with KCPP_APPEND (For example if someone wants to make an unofficial build).
- Created duplicate versions of the existing CUDA CI's with the CUDA version changed

Keep the following in mind:
- To help differentiate, Koboldcpp.sh is now scripted to always append the cuda version to the output binary. This does mean I have to update https://koboldai.org/cpplinux once this is live if you upload them as is, if you use a direct link elsewhere the readme has to be updated to.
- Windows Full CI hasn't been duplicated yet, ill leave that one up to you since you made it.
- CUDA 12 version I went with is 12.1 to keep it the same as the one torch uses (Maximizes compatibility with cloud providers and others who may want to integrate). 
- We should keep providing the CUDA 11.4 / 11.5 binaries due to their smaller size, compatibility with older GPU's and cheap hosting options such as VastAI.

### CODE REVIEW

**Comment by LostRuins** [comment]
I'm thinking for the binary filename we can leave the old name to be the same as it was for CUDA11, to avoid breaking any existing links or workflows. 

The CUDA 12 version can be created with the new suffix instead. 

So the "default" normal build is the same as before (CUDA11) and then people who need cuda12 and don't mind massive files can get the oversized version.

**Comment by LostRuins** [comment]
Let me get 1.64 release out first.

**Comment by henk717** [comment]
This would enable a 1.64 cuda 12 build for Linux.
Old binary name is a bit trickier in the way I built it but it could be done with additional if statements.

**Comment by LostRuins** [comment]
What do you think of the naming?

**Comment by LostRuins** [comment]
we can just add an extra line to rename the file

**Comment by LostRuins** [comment]
Is it ready to merge?

**Comment by henk717** [comment]
Yes

**Review by LostRuins — APPROVED** [review]

**Pull request merged**
