### PR TITLE
New UI using customtkinter

### PR DESCRIPTION
**Pull request by Vali-98**
image

A new UI for launching when launching without parameters, utilizing customtkinter:
https://github.com/TomSchimansky/CustomTkinter

Features:

- Supports all parameters for launching koboldcpp (Aside skiplauncher)
- Allows saving and loading batch / shell files 

This should also fallback to the old UI if customtkinter is not installed.

### CODE REVIEW

**Review by LostRuins — APPROVED** [review]
seems to be working fine now

**Comment by LostRuins** [comment]
merged

**Comment by clort81** [comment]
How do I install customtkinter for koboldcpp?
Either in the conda container or outside of it, pip3 install customtkinter fails on my system.

**Comment by LostRuins** [comment]
you're going to have to be more specific. customtkinter can be installed by pip on most systems. Why does it fail?

**Pull request merged**
