### PR TITLE
Allow launching the GUI if a settings file was used

### PR DESCRIPTION
**Pull request by Limezero**
### The problem:

I want to be able to load my settings from a `.kcpps` config file (as the "Load" button in the GUI does), but *without* starting the model and inference (as the `--config filename.kcpps` flag does).

This is useful because I frequently find myself swapping out models, but I have a common configuration shared between all of them which isn't likely to change. Having to click the "Load" button and navigate to the directory where I saved my `defaults.kcpps` every single time I run KCPP is extremely tedious, as is having to create dozens of copies of my config file like `model_1.kcpps`, `model_2.kcpps`, `model_2_Q8.kcpps`, `model_2_Q4.kcpps` and so on.

I took a look at the source code of koboldcpp.py, and it is... a bit of a mess, to put it lightly, but nevertheless I tried my hand at implementing the above while doing the least damage possible.

### This PR makes two changes:

1. It adds a new `--showgui` flag with a boolean value which forces the display of the GUI even if a .kcpps file was selected through `koboldcpp filename.kcpps` or `koboldcpp --config filename.kcpps`. I chose the name `showgui` for the flag since `gui` felt a bit too "important" to use, `forcegui` felt a bit too "programmer-y" for the average user, and `skiplaunch` would conflict with the existing flag `skiplauncher`. Feel free to pick something else though.

2. It makes the `load_config_cli()` function store the filename it used into a global variable, so we can use it to populate the values of the GUI before it starts rendering (by loading said file again and parsing it from scratch). This works, but it's a VERY ugly hack. Ideally, we'd call a simple `refresh_gui_values()` function here which applies the values already loaded into `args` to the GUI sliders and boxes, but I wasn't able to find the equivalent of that function (`gui_changed_modelfile()` doesn't seem to be enough). If it does exist, please use that instead. I opted to avoid modifying `load_config_gui()` to take a `filename` parameter like its CLI counterpart and calling that function, but if the `runmode_untouched` variable it sets is meaningful for this, then it might be worth doing that instead.

From my limited testing, everything seems to be working, but I'm not familiar with the codebase, so it's likely that I missed something obvious. As I said, all of this is hacky to the extreme.

### CODE REVIEW

**Comment by LostRuins** [comment]
Hi, thanks for the PR, I decided to go with a more general solution https://github.com/LostRuins/koboldcpp/commit/68aee5649868e37e92c3b1f91627a04356b4252f

This will allow you to import any command line arguments into the GUI with `--showgui`, including the config files. So you could do `koboldcpp.exe --usecublas --gpulayers 20 --showgui` and it would open the GUI and attempt to import the flags

If you'd like you can test it first, otherwise you can wait for the next release which will be coming soon.

**Comment by Limezero** [comment]
@LostRuins Hey, that seems to be working, thanks. Two additional designs/issues I've thought of since:

1. As far as I can tell, the intention with your implementation is to be able to define ad-hoc settings through the command line (*instead of* loading a `.kcpps`) and show the GUI with those pre-set. Which is fine, but it might also be worth having the manually specified parameters override what was loaded from a `.kcpps`, rather than the other way around. When launching from SSH for instance, this would allow someone to do `koboldcpp --config hundreds_of_settings.kcpps --model file.gguf --contextsize 4096`, i.e. load a bunch of defaults and then override them on a case-by-case basis. This is your only option when working from a terminal, since manually typing out dozens of settings or editing the JSON would be tedious.

2. Independent to all this, the most sensible thing to do might be what every other application does - save the last used GUI values into a file, then load those on the next launch. Specifying anything through a terminal launch could then ignore that last state, and use, in order: Manually specified `--flag <val>` values -> What was supplied in a `.kcpps` file -> Defaults

Thoughts?

**Comment by LostRuins** [comment]
1. Hmm perhaps, but for backwards compatibility reasons changing it now would not be a great idea, as it would break a lot of people existing setups. What you can try to do is to remove the key from the kcpps file manually, that should prevent it from being overwritten.
2. Autosaving settings is tricky, since KoboldCpp is intended to run portably, with support for multiple instances, and there is no good place to store settings, also people might not want it writing to disk on it's own.

**Comment by Limezero** [comment]
1. I'm not sure I get that, if loading a `.kcpps` currently overrides everything else, who out there is passing koboldcpp.exe command-line flags which they *expect* to be discarded? Removing the key is not a great workaround, since you might not know in advance which specific setting you want to deviate from on that launch, and takes us back to having to juggle multiple .kcpps files on disk. Again, this behavior matches most GUI applications out there, when I launch my browser or text editor with a `--do-something-different` flag, I don't expect it to discard all of my settings and start with a brand new empty profile, nor do I expect that flag to be ignored because my settings happened to already be storing the default value of that key.

2. Would storing a simple `settings.kcpps` file next to the `.exe`/`.py` not work? Sure, it might be confusing if someone were to move their koboldcpp.exe to a different folder and their settings disappeared, but... their settings *already disappear every time*? And having to store multiple `.kcpps` files or shortcuts in order to avoid having to set every single parameter manually is already the case, so koboldcpp.exe **actually** being a standalone, single .exe file which can be moved anywhere is rarely the case for most serious users. (Plus we already have the "extract files from the exe" option.)

I'm fine with putting all of these behaviors behind some super secret advanced power user flag, or only triggering them if the user knowingly performs a task like creating a file and naming it a certain way, but I don't think those are good reasons not to have the features altogether.

**Comment by LostRuins** [comment]
Fair point. It is actually not very easy to implement - it's hard to tell an explicitly parsed argument from one that has been passed over the CLI. For example, the default value of contextsize is 4096. The user can override that with `--contextsize X`. However, they can also pass in `--contextsize 4096` and I cannot tell the difference between that and the default.

I can implement a primitive version of it that matches raw args directly, so if you set `--gpulayers 10` it would override the one in the kcpps file. However, since argparse allows for autocompletion, it would fail if you set the command line to `--gpulay 10` even though that's a legal shorthand flag in argparse.

**Comment by Limezero** [comment]
I can try writing a separate PR for both of those features, if you want (since I'm already going to be implementing them for my personal use).

Yeah, the use of argparse complicates things somewhat. Especially if "set-to-the-default-or-the-args" happens in a single step, and all you can check afterwards is whether each individual value currently matches its default or not. I'll have to look into that. 

Though even if none of this is implemented, I think the current state of things would at least warrant some sort of `Hey, you're trying to pass a config AND also specify command line flags, just so you know, all of those will be ignored` warning message, since that tripped me up. It makes sense since you can create a `.kcpps` file with only one setting in it, but I'd wager the few people who even know about this feature end up using it with the auto-generated files you get from the GUI's save button, and assume that's how they're meant to be formatted. Pure conjecture on my part though, obviously, if other people you've spoken to find it intuitive then fair enough.

-----

Regarding autosaving settings, what do you think about a design similar to what some applications use for enabling their "portable mode"? That is, the feature is documented and available, but in order to enable it, the user must on their own create a file named `something.ext` next to the executable of the application, which checks whether that file exists on launch. KCPP could check the presence of a file (say, `koboldcpp.kcpps` or `.last_state.kcpps` or something else), and if that file exists, 

- It gets loaded on launch (only if we're running in GUI mode)
- If it got loaded, the action that would be triggered by the `[Save]` button in the GUI gets triggered to that file upon koboldcpp's exit cleanup process

It would require users to opt-in explicitly by creating that exact filename in advance (so no leaving unwanted files behind), it allows one to ignore it even if it's present by explicitly loading a different file (via the `[Load]` button or CLI), and it wouldn't interfere with multiple instances (since those would already need to be launched with explicit settings due to conflicts with the `:5001` port if no other reason).

**Comment by LostRuins** [comment]
Sure, feel free to take a look at the current implementation at https://github.com/LostRuins/koboldcpp/blob/concedo/koboldcpp.py#L3749

I'll think about the settings thing. Still not a big fan of automatically persisting settings onto a user's device.

**Comment by Limezero** [comment]
Of saving a file onto a user's device, or of persisting the settings in general?

I'd be curious to know if no one else has complained about this before, the seemingly intended workflow of
- Launch koboldcpp
- Select the backend
- Select the GPU
- Enter the number of layers (hope you remember the value you figured out last time)
- Click the other options you want
- Drag the context size slider
- Go to the hardware tab to see the options not on the main page
- Set the threads
- Go to the tokens tab
- Enable KV cache quantization
- Wait where's the model section
- Oh right that was on the main page, go back to "Quick Launch"
- Browse
- Damnit, it put me on my desktop, where did I save my AI models
- Other drive, AI folder, models, LLMs... which one did I use last time, was it the Q4_K_M or the Q4_K_S?
- Launch

...is a bit annoying. Especially after finding out that you forgot to close something, so koboldcpp crashed with an OOM and you get to perform every single one of those wonderful steps all over again.

**Comment by LostRuins** [comment]
Understandable. For me I have a .kcpps of all my favorite models and setups in a folder next to where I put the exe. I just drag and drop it in and boom, ready to go.

**Comment by Limezero** [comment]
That's what I've been doing (with scripts even before the .kcpps system became a thing), but it's become an ever-increasing nightmare to maintain as I get more comfortable with the settings.

2024 09 22-07 38 07_explorer

For instance, I recently disabled the "Launch Browser" option because it was annoying me, but I already had a ton of presets for various models created over the last year. So if I find myself going back to a model I used a month ago to test something, wait, why is it launching the browser again, didn't I already disable that? Oh right, because I'd need to go back to all of those configs and individually change the setting to false in every single one of them. `.kcpps` presets which only specify the model name/ctxsize/layers could help - except they don't, because I still have no way of specifying my common settings other than creating dozens of batch/shell scripts.

Or, I have a Nemo finetune which I've been using daily for a month, but I want to test a different one. Great, now I have to duplicate the config file. Maybe I want to test different quants, so I need to create five more, even though the settings are going to be identical in all of them except for the filename. Damnit, I forgot to change the filename in one of them so my `nemo_12b_q6` config was actually loading the Q4 version this whole time.

Sorry for the rants out of nowhere, I've just been frustrated by this for the better part of a year now.

**Comment by LostRuins** [comment]
Hopefully the showgui option makes it easier for you.

A bit clunky, but find and replace works well too, kcpps files are just text after all.

**Pull request closed without merging**
