### PR TITLE
implement sampler order, expose sampler order and mirostat in api

### PR DESCRIPTION
**Pull request by ycros**
I've tested both the normal case, sampler ordering and mirostat.

### CODE REVIEW

**Comment by LostRuins** [comment]
Heyo. Adding the sampler order parameter should be fine, but have you tested what happens when these extra new fields for mirostat get sent to regular kobold via API? 

IIRC regular kobold will crash on receiving unknown fields - if that's the case maybe they should be added to a separate endpoint (maybe ` POST /api/extra/config/` with a set of setting values?) rather than extending the current `/api/v1/generate` one. 

Or, United would have to gracefully handle these new fields to maintain compatibility.

What do you all think? @ycros @henk717

**Comment by ycros** [comment]
Yeah, I've been running some of my own code against the API so I wasn't really thinking of the UI when I added it (although I did test lite, since it already sends sampler order).

Wouldn't the UI already have to know that it's talking to kcpp or something that supports these extra args in order to decide to post to another endpoint vs... deciding to include these in generate? I guess I don't actually know how rigid the current API schema here is.

**Comment by henk717** [comment]
I think the right design would be as part of the generate call, if KoboldAI crashes on this we will have to patch that.

**Comment by LostRuins** [comment]
@ycros refactored some code to remove duplicate sampler calls, pushed to your PR branch and my experimental branch. Help me check if everything works as expected.

**Review by LostRuins — APPROVED** [review]

**Comment by ycros** [comment]
I checked the code, re-tested mirostat/sampler order - all looks good.

**Pull request merged**
