### PR TITLE
docs(README.md): add guide for nix and nixos

### PR DESCRIPTION
**Pull request by FlameFlag**

### CODE REVIEW

**Comment by LostRuins** [comment]
Hi, thanks for the contribution: 

I tried to compact it a little as it's a bit too verbose, considering that the readme is already very long. If you have external documentation for nix, i'd be happy to link to it!

If I got something wrong, do let me know!

**Review by LostRuins — APPROVED** [review]
I'll merge this in a bit if there are no issues on your end.

**Comment by FlameFlag** [comment]
I actually have one small note to add on my end

**Comment by FlameFlag** [comment]
@LostRuins You can merge it

**Comment by FlameFlag** [comment]
> I tried to compact it a little as it's a bit too verbose, considering that the readme is already very long. If you have external documentation for nix, i'd be happy to link to it!

I shortened it a bit.

> If you have external documentation for nix, i'd be happy to link to it!

I added a link to Nix Pills that explains overriding packages in further detail

**Comment by LostRuins** [comment]
You just forced pushed the branch, overwriting all my changes

**Pull request merged**
