### PR TITLE
Dynamic sizes for sequences

### PR DESCRIPTION
**Pull request by mayaeary**
Make dry sequences, stop sequences, logit biases and banned strings to be allocated dynamically, to get rid of hard limit.

### CODE REVIEW

**Comment by LostRuins** [comment]
Hm, I don't think this is a good idea. Feels like it'll be prone to either memory leaks when the container gets resized, or going out of scope prematurely. Especially since I don't have control of when gc happens

**Comment by LostRuins** [comment]
Will review this again when I have some time to test - hang tight for now

**Comment by stepfunction83** [comment]
Could it be possible to specify this as a launch parameter to avoid any dynamic sizing issues?

**Comment by LostRuins** [comment]
Hi @mayaeary made some small tweaks, think this should be good to go.

**Pull request merged**
