### PR TITLE
Add --checkforupdates argument, hipBLAS autopicking and hipBLAS .kcpps bug fixes

### PR DESCRIPTION
**Pull request by YellowRoseCx**
When importing a .kcpps file with the backend Use hipBLAS chosen, it would not select Use hipBLAS. This change corrects that.

If enabled, the argument --checkforupdates will fetch the KoboldCpp release page(via Github API) one time on start up via HTTPS and compare the latest version number with the current version number and notify the user if a new version is available. 
A GUI button is shown on the Network tab. Disabled by default.

Fixed a mistake preventing hipBLAS from being autopicked on startup

### CODE REVIEW

**Comment by LostRuins** [comment]
can I modify this to grab the fix PR for the HIPBlas bug fixes first? 
or split it into 2 PRs?

I'm not so sure about the update checking stuff cause:
1. it adds 2 more non-default python module dependencies.
2. it requires a sync fetch, slowing down the execution/launch and possibly causing issues if they are not actually connected to the internet or on a slow network.
3. It seems kind of unnecessary. There's already an update button in the GUI. It simply directs them to the repo to download the a new version.

**Comment by LostRuins** [comment]
Cherry picked the HIPBlas fixes in https://github.com/LostRuins/koboldcpp/commit/852ca780c97e0fc8a34b6fe4237ec4a00a207897

**Comment by YellowRoseCx** [comment]
> can I modify this to grab the fix PR for the HIPBlas bug fixes first? or split it into 2 PRs?
> 
> I'm not so sure about the update checking stuff cause:
> 
> 1. it adds 2 more non-default python module dependencies.
> 2. it requires a sync fetch, slowing down the execution/launch and possibly causing issues if they are not actually connected to the internet or on a slow network.
> 3. It seems kind of unnecessary. There's already an update button in the GUI. It simply directs them to the repo to download the a new version.

The reason I made the check for updates argument was because the update button doesn't change color or notify when an update is available. I thought it only needed urllib3 added? Whats the second dependency?

**Comment by LostRuins** [comment]
> what's the second dependency

urllib is fine as it's part of the default actually, the extra ones are `colorama` and `requests`. 

> I think the way it was done didnt count as a commit from my account in terms of contribution count

ah probably because I added and merged the specific changes as a patch instead of a whole commit. If you'd like, you can resubmit the changes as a separate PR and I'll merge that so you get the contrib.

**Pull request closed without merging**
