### PR TITLE
Mac builds

### PR DESCRIPTION
**Pull request by henk717**
With some help of M.Holy I managed to find the issue with the metal pyinstaller, this CI should build and then test the binary for MacOS.

Mac still needs some overhauls for the UI since they can't input the gpulayers, and ideally we find a way to auto detect layers. But for now this at least allows binary builds.

### CODE REVIEW

**Comment by LostRuins** [comment]
Very nice - what error happens if tkinter is loaded?

**Comment by henk717** [comment]
No error metal just needs its own backend screen with GPU layers exposed. No Blas is not a good fit for it.

**Comment by LostRuins** [comment]
Oh, but this currently has no metal support correct?

**Comment by henk717** [comment]
It does, it works as well as the non prebuilt does we solved the issues with metal.
Can be merged as is, but I recommend making a GUI for Metal prior to releasing binaries.

**Pull request merged**
