### PR TITLE
Search for cuda_path on Windows

### PR DESCRIPTION
**Pull request by jojorne**
Let's add dll directory for cuda on Windows too.

### CODE REVIEW

**Comment by jojorne** [comment]
I also delete the two cuda dlls (cudart64_110.dll, cudart64_12.dll) shipped with the repository so it can find the ones installed by my cuda installation. So changing the search path order will affect this.

**Comment by jojorne** [comment]
.gitignore
```
/cublas64_11.dll
/cublasLt64_11.dll
/cudart64_110.dll
/cublas64_12.dll
/cublasLt64_12.dll
/cudart64_12.dll
```
It would become unnecessary.

**Comment by LostRuins** [comment]
Thanks, will take some time to review this later

**Comment by jojorne** [comment]
btw this works too:
`pip install nvidia-cublas-cu11 nvidia-cuda-runtime-cu11 --index-url https://download.pytorch.org/whl/cu118` 
`pip install nvidia-cublas-cu12 nvidia-cuda-runtime-cu12 --index-url https://download.pytorch.org/whl/cu121`

Then we look inside the `site-packages\nvidia\cublas\bin` and `site-packages\nvidia\cuda_runtime\bin`.

_These packages are intended for runtime use and do not currently include developer tools (these can be installed separately)._ - CUDA Installation Guide for Microsoft Windows

**Comment by jojorne** [comment]
The python cuda runtime is out of question?

**Pull request merged**
