### PR TITLE
expose some time info from c++ 

### PR DESCRIPTION
**Pull request by callMeMakerRen**
currently, the prompt process time and prompt eval time is calc and print in c++, and not expoed to python, which is not convenient for performance compare , so i expose the time that are useful, and in python side i can call the api multi times and compare the time , if there is some way better ,please tell me.

### CODE REVIEW

**Comment by LostRuins** [comment]
do you need the individual time, or just the total time? 

because if total time, you can just run a timing function on the client side when you call the API, and count total time when it returns. For example, Kobold Lite GUI does that, it measures time in browser.

**Comment by callMeMakerRen** [comment]
i think we need individual time, because prompt process and prompt eval is not the same function, the time can vary for different length prompt that feed in, and not only prompt eval is import ,but the prompt process time is much longer in real world, individual time can help us to improve the performance with a baseline test, if any useful advice, please let me know.

**Comment by LostRuins** [comment]
okay will review and merge sometime soon

**Comment by LostRuins** [comment]
Instead of directly modifying the generate API, I'm moving the timing functions into a separate API call, which will be accessible from `/api/extra/perf`, and will contain both timings (and possibly more performance information) in the future.

Integrated and will be merged into next release.

**Pull request merged**
