### PR TITLE
Proper SSE Token Streaming

### PR DESCRIPTION
**Pull request by SammCheese**
This PR Implements a server-sent event token stream on POST `api/extra/generation/stream`
Backwards compability has been implemented and (hopefully) causes no issues for existing Applications interacting with the API.

The token streaming implementation itself is very simple to use.

Send a POST request to `api/extra/generation/stream` and the api will respond with an event stream in the following format:

```
event: message
data: {"token": "SomeToken"}
```

It will continuously push the event every time a new token has been generated along with the token that has been generated and close the stream once the generation request is completed.

### CODE REVIEW

**Comment by LostRuins** [comment]
Hi, took a quick look and it seems potentially workable. 

Recommend a few changes if possible: 

1. Possible to replace aiohttp as it is a non-default dependency? Instead, `text/event-stream` can be implemented directly in python `http.server`, see  https://stackoverflow.com/questions/27639356/python3-4-read-content-stream-web-request , same reason why I avoided using Flask in the first place. This makes installation for linux and OSX users much easier because they don't have to worry about installing any requirements, even tkinter is also optional. Should be quite straightforward, let me know if it doesn't work for some reason.
2. There is a potential race condition with your implementation - right now `receive_current_token` overwrites the new token with another token every eval cycle. If the model is very fast (e.g. 50 tokens per second) you cannot guarantee that `new_token()` is called in time from Python before the previous token gets overwritten, potentially dropping some incoming words. It is also technically unsafe to modify `new_token_available` on both threads (python + CPP) since it is not atomic. A better implementation is for the Python side to be read-only, `new_token()` should not mutate the C++ state. Instead, store a vector/array of std::strings on the C++ side, emptied at the start of a new generation. On the Python side, manually record an index for which token position you are currently reading. At generation time, C++ will simply push new std::strings into this vector. Then you will call new_token(idx) and read the correct element from the C++ side. E.g. to read the 5th streamed token, call new_token(4), which reads the 5th std::string element in the token array. You can store the vector length separately or return null if the requested token hasn't been generated yet.
3. `set_stream_finished` export is unnecessary. It can be set from the C++ side on the start of a new generation if SSE is enabled. Same for `bind_set_stream_finished`, what is that even for?
4. `is_locked` can be changed to `get_stream_count` to get the current number of completed tokens, as described in point 2.
5. No reason to expose `receive_current_token`, it's not used externally. Just use a std::vector<std::string> for the stream output buffer and write to it, should not be part of the API.

That's all the stuff I can think of for now.

**Comment by LostRuins** [comment]
Also you might wanna rebase because I realized from your PR that I had a ton of trailing whitespaces which I've removed.

**Comment by LostRuins** [comment]
Hi @SammCheese I've added the fix for termination of connection it seems to work. Have merged this into my branch, please test if it works for your Agnai client.

**Comment by AlphaAtlas** [comment]
Is this something that could work with the built-in kobold UI?

**Comment by LostRuins** [comment]
Yes, I plan to integrate it in the coming days

**Comment by LostRuins** [comment]
If someone could revisit and test this, it would be great, as I've heard that SSE streaming to agnai no longer works.

**Pull request merged**
