### PR TITLE
feat - series of changes to enhance the compability with KoboldHorde…

### PR DESCRIPTION
**Pull request by gustrd**
…. Now can receive parameter of modelname, maxlen e maxctx, avoiding timeouts.

Changed the default modelname to KoboldHorde's default format.

### CODE REVIEW

**Comment by gustrd** [comment]
I tested with https://lite.koboldai.net/# , and it  is working fine.

Em sex., 14 de abr. de 2023 às 12:20, LostRuins ***@***.***>
escreveu:

**Comment by gustrd** [comment]
Okay, I will try it.

Gustavo Rocha Dias


Em sex., 14 de abr. de 2023 às 12:28, LostRuins ***@***.***>
escreveu:

**Comment by gustrd** [comment]
You are right, if I use the "Online Service/API" option at KoboldAI United
I get the error:

OSError: KoboldCPP/gpt4-x-alpaca-13b is not a local folder and is not a
valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having
permission to this repo with `use_auth_token` or log in with
`huggingface-cli login` and pass `use_auth_token=True`.

I checked that you created a placeholder at
https://huggingface.co/concedo/koboldcpp . So my proposal is to change back
the default model name to "concedo/koboldcpp" , to allow the
compatibility with KoboldAI United. The parameter is renamed to
"--kobold_horde_model_name"
and shall be used only when using via HordeBridge.

The MaxToken and MaxContext parameters as a view then are "upper caps", the
client can request less than then, but if the client tries a bigger value
they will be capped, avoiding memory overflow and timeout.

Can you check the updated PR?

Em sex., 14 de abr. de 2023 às 12:43, Gustavo Rocha Dias ***@***.***>
escreveu:

**Comment by LostRuins** [comment]
Also I am slightly concerned that this will be disruptive to the Horde, as CPU workers are practically too slow to run effectively and will degrade the experience of others trying to use the same model. So I am wary of support Horde out of the box.

**Comment by gustrd** [comment]
I understand your concern, but I'm having a speed of around 1.0, what gives
a response each 60 seconds, very near Horse's average, if you consider
queues.

Many people already use the Horde with GPU sharing memory with normal RAM,
what gets almost the same speed, and is supported by KoboldAI United.

So I don't think that is so disruptive. Also the Horde already disconnect
those with speed under 1 automatically, and it's an easy to adjust
parameter for those serving it.

Em sex, 14 de abr de 2023 23:33, LostRuins ***@***.***>
escreveu:

**Comment by henk717** [comment]
Horde does have some defenses against this, if the speed drops below what we consider acceptable a worker is blocked.

**Comment by LostRuins** [comment]
@henk717 i'd like to defer to your judgement on this - do you think this is a good idea to allow 
1. koboldcpp to be easily used on horde 
and
2. people to easily set arbitrary display names on the model (since KCPP will have no way to verify anything)?

**Comment by gustrd** [comment]
Just to humbly add, with all respect, currently both are already possible
(1. with concedo's name and 2. with minimal code change).

Em sáb., 15 de abr. de 2023 às 13:51, LostRuins ***@***.***>
escreveu:

**Comment by LostRuins** [comment]
@gustrd I know, none of these are intended or able to stop users, considering the entire project is open source and freely modifiable, same as the horde worker for that matter. 
But we have to find approaches that promote the kinds of user behavior we want to have.

**Comment by gustrd** [comment]
I understand.

To mitigate bad behavior or fraud I put the prefix "KoboldCPP/" before the
given model name, warning the users that it's not the usual KoboldAI.

I can implement any other suggestions going this way.

Em sáb, 15 de abr de 2023 14:16, LostRuins ***@***.***>
escreveu:

**Comment by gustrd** [comment]
@LostRuins and @henk717 , do you guys have something else in mind?

Maybe getting the actual parameter's number from the loaded model would help? This may avoid someone telling they are running a bigger model than they really are, per example.

**Pull request closed without merging**
