### PR TITLE
Add GPTLocalhost as third-party resource

### PR DESCRIPTION
**Pull request by GPTLocalhost**
Thank you for this repo. I have integrated KoboldCpp with Microsoft Word through a local Word Add-in. Is it possible to add this Word Add-in in README so that users have one more reason to try KoboldCpp? Thank you for your consideration.

### CODE REVIEW

**Review by LostRuins — COMMENTED** [review]
Sure. I might move it to a different subsection later tho

**Comment by leejason** [comment]
Appreciated.

**Comment by GPTLocalhost** [comment]
Appreciated.

**Comment by GPTLocalhost** [comment]
BTW, the demo of integrating KoboldCpp with Microsoft Word has bee uploaded to YouTube [here](https://youtu.be/_E0jnRsoyHg).

**Pull request merged**
