### PR TITLE
Entropy sampling / Greedy dynamic temperature (DynaTemp)

### PR DESCRIPTION
**Pull request by kalomaze**
Initial 'greedy' implementation of Dynamic temperature with hardcoded values. I think I moved around two unrelated functions for other samplers (TFS?) because it was easier to edit like that, will put them back later ig.

### CODE REVIEW

**Comment by kalomaze** [comment]
The scaling exponential curve might be working backwards, but I'm not sure. I'll continue to double check.
image
This is how it should be scaling assuming `k = 2`

**Comment by kalomaze** [comment]
image
The PR's default values should now properly reflect this graph.

**Comment by kalomaze** [comment]
This latest commit ^ changes more than just that, sorry for the poor title. The temperature value '1.93' has been temporarily hardcoded as the option for 'Max temp 1.5' with a k scale of 10. 1.94 is for 'Max temp 2.0' with the same k scale. Both of them plot the center smack dab in the middle of the temp range.

image
image

**Comment by LostRuins** [comment]
i plan to add an `--experiments` flag where weird stuff like this can be optionally enabled for those user who want to try it. This flag parameters will be temporary and subject to change. if you are satisfied with your implementation let me know, and i'll review and add it as an optional toggle.

**Comment by LostRuins** [comment]
I don't think this should be considered as a full standalone new sampler yet at this stage, for a few reasons:
1. It has not had widespread testing, or been proven to work.
2. To be an independent sampler:
    - this sampler must be able to work in conjunction with any/all other samplers, in any order. Since it replaces temperature, this is not possible. It would have to be functional alongside regular temperature which doesn't really make sense
    - it would have to have a scalable value that disables it, and gradually activates as the config differs from this value. For temp, top_p, and rep_pen, that value is 1.0, for top_a, that value is 0.0. However your sampler is affective across all values.
    - it would need to work for any range of logit values and any number of candidates (include 1 and 0), since other samplers may have pruned the candidates before reaching yours.
3. Additionally, to get a new sampler ID, it would be necessary to gracefully handle it (e.g. sampler id 7) on horde or other backends such as KAI united, since right now all of them expect exactly 7 samplers [0-6], adding one extra index causes all sorts of issues.

This is why **mirostat** is not a new sampler either - it is a toggled mode (sampler replacement).

What would probably work better if this proves useful, would be an API param (similar to mirostat and token unbans) that indicate to a backend to use this alternative dynamic temp. sampler in lieu of normal temperature sampling. Backends that do not recognize it will have their temperature values  handled normally. But before adding to any API spec, it should be testing via optional experimental flags first (same as usemirostat once was).

**Comment by kalomaze** [comment]
> I don't think this should be considered as a full standalone new sampler yet at this stage, for a few reasons:
> 
> 1. It has not had widespread testing, or been proven to work.
> 2. To be an independent sampler:
>    
>    * this sampler must be able to work in conjunction with any/all other samplers, in any order. Since it replaces temperature, this is not possible. It would have to be functional alongside regular temperature which doesn't really make sense
>    * it would have to have a scalable value that disables it, and gradually activates as the config differs from this value. For temp, top_p, and rep_pen, that value is 1.0, for top_a, that value is 0.0. However your sampler is affective across all values.
>    * it would need to work for any range of logit values and any number of candidates (include 1 and 0), since other samplers may have pruned the candidates before reaching yours.
> 3. Additionally, to get a new sampler ID, it would be necessary to gracefully handle it (e.g. sampler id 7) on horde or other backends such as KAI united, since right now all of them expect exactly 7 samplers [0-6], adding one extra index causes all sorts of issues.
> 
> This is why **mirostat** is not a new sampler either - it is a toggled mode (sampler replacement).
> 
> What would probably work better if this proves useful, would be an API param (similar to mirostat and token unbans) that indicate to a backend to use this alternative dynamic temp. sampler in lieu of normal temperature sampling. Backends that do not recognize it will have their temperature values handled normally. But before adding to any API spec, it should be tested via optional experimental flags first (same as usemirostat once was).

Given the difficulty of implementing a new sampler due to how the sampler stack currently operates, I have reworked it to use a text file in which you can customize the values that it uses while the software is running:

image

Now, turning the temperature to 2.0 will work as a 'toggle' and the values can be controlled by the end user, without affecting the typical sampler procedure (when using normal temp values).

Does this seem like a good compromise for doing testing without changing too much of the code?

**Comment by LostRuins** [comment]
text file is not a good idea either, because pyinstaller runs from a temporary directory and file paths are relative to it vs the script directory it won't be able to find your file unless the path is explicitly provided. If you need parameters for it, that can be easily added as arguments for that experimental flag, or as a subparser.

**Comment by kalomaze** [comment]
> text file is not a good idea either, because pyinstaller runs from a temporary directory and file paths are relative to it vs the script directory it won't be able to find your file unless the path is explicitly provided. If you need parameters for it, that can be easily added as arguments for that experimental flag, or as a subparser.

I wanted to avoid needing to modify frontends like SillyTavern so that they support new arguments.

**Comment by kalomaze** [comment]
> you don't have to modify the ST frontend. Just adjust your launcher parameters with koboldcpp - you already do that to select number of GPU layers, threads etc

Being unable to modify without reloading the entire model when testing different settings is quite inconvenient

**Comment by kalomaze** [comment]
> you would have the same issue when reading from a file.

Could you point me towards the simplest way to implement it like that that would be easier than just telling my testers to go to %appdata% and locate the temp path?

**Comment by kalomaze** [comment]
> it won't be able to find your file unless the path is explicitly provided

image
I thought the same thing but apparently not! 

https://github.com/kalomaze/koboldcpp/releases/tag/gini-entropy-v1

**Comment by lofcz** [comment]
@kalomaze this looks interesting, do you intend to merge upstream?

**Comment by aleksusklim** [comment]
@kalomaze, I tried your mod on my usual setup with `mythalion-13b.Q5_K_M`
My usual sampler settings are:
- top_p = 0.85
- temperature = 0.85
- rep_pen = 1.1
- rep_pen_range = 1024

I also tried Mirostat before, and it looks very boring, as if temperature was always zero. (Yeah, there was a bug when the temperature indeed was zero, but then it got fixed and I rechecked; turns out it still gives much less randomness, which might be useful for factual answers, but ruins the fun of any role-playing).

And I tried TFS once, which I thought would be better than Nucleus top_p, but in practice it did something to model's understanding of conversation format, so it started to write passages of text without stopping or switching turns (as if the temperature was too high).

Now I tried your Gini / whatever, with your default .txt using temperature=2.
I left my top_p on 0.85. I saw in console how it's changing the temperature on demand.

The text looked good! I regenerated the same response several times with temp=0.85 (my setup) and temp=2.0 (your setup) to compare, which mode gives more pleasant output with higher chance.

But… My temp&top_p=.85&.85 is already worked good enough to almost always give high-quality and at the same time pretty random responses, and your method didn't give anything outstanding to this. (But for sure it did not break anything and didn't make it worse).

Then I remembered that you proposed your method as a replacement for Repetition Penalty, so I changed that from 1.1 to 1.0 and continued playing at my 0.85/0.85.

I noticed the model now had a tendency to repeat the same phrases, and the same words combinations appeared more often. Output was slightly less random.
Then switched to temp=2.0 and continued with your method.

Looks like from that point, everything became normal again, I didn't notice that much of repetitions (which is pretty good, since I did not remove previous repeats from the history, that made the overall quality of the story slightly lower).

I think we need to compare top_p (w/ and w/o rep_pen) at constant temp against the dynamic temp more closely. Currently you are printing only token probabilities but not the tokens themselves.

Can you somehow collect the probability for each meaningful token before and after temperature rescaling, along with token text? And output only those (optionally with a key in .txt), for example:

0.940 -> 0.760 | You
0.059 -> 0.210 | After
0.001 -> 0.030 | So

(This is just an example, real probabilities here would be changed the other way around).
This way we would see, which words are getting discarded/added with dynamic temperature. Then it would be possible to pick those words manually to put them in history – to continue further, simulating as if that particular token was chosen.
(Or to predict just a few tokens and regenerate several times).

We should confirm three things:
1) That bad and incorrect tokens are not increasing.
2) That good rare tokens becoming more probable, leading to diverse and coherent texts.
3) That this is better than any constant temperature with any constant rep_pen.

Checking the exact list of tokens at each step is way more precise than regenerating and comparing results subjectively.

**Comment by aleksusklim** [comment]
I've noticed your Min-P sampling strategy and downloaded `koboldcpp_API_minP_LATEST.exe` to try it on `llama2-13b-tiefighter.Q6_K.gguf`

I asked it to write long stories with Alpaca instruction format. The result was excellent no matter what setting I'm trying: low temp (0.01), high temp (1.98), Min-P (0.02-0.05, 0.9), Top-P (0.85), HHI (at your default). Looks like when the model is good, its goodness pays off for any subtle sampling differences.

(I double-checked that the text was similar at low temperature, and that with Min-P and HHI there are additional output in the console each step).

Can we implement an "inverted sampling" flag that flips the probabilities of the final available limited token set?
For example, if the model, after all sampler manipulations (top_k, top_p/min_p, temp), gives these probabilities:
"A" = 80%
"The" = 15%
"It" = 4%
"So" = 1%
– Then this inverted sampling would flip its values:
"So = 80%
"It" = 15%
"The" = 4%
"A" = 1%

This way instead of "often best case and rarely bad choices" we will do "often worst case and rarely good choices" – to force the model to pick infrequent but available (by current sampler set) tokens. So we can compare, "how much bad" they are!

**Pull request closed without merging**
