### PR TITLE
Add Multi-GPU CuBLAS support in the new GUI

### PR DESCRIPTION
**Pull request by YellowRoseCx**
This adds on the option to select "all" CuBLAS GPUs when loading the program using the new GUI

### CODE REVIEW

**Comment by LostRuins** [comment]
Duplicate for https://github.com/LostRuins/koboldcpp/commit/8edcb337c6e763beea97f2a604480cb8f8a62825 , already added in experimental.

**Comment by YellowRoseCx** [comment]
> Duplicate for [8edcb33](https://github.com/LostRuins/koboldcpp/commit/8edcb337c6e763beea97f2a604480cb8f8a62825) , already added in experimental.

Won't those changes show an "All" option for CLBlast which doesn't support more than 1 GPU?

**Comment by LostRuins** [comment]
You are correct. Let me review this again.

**Comment by LostRuins** [comment]
Integrated and will be merged into next release

**Pull request merged**
