### PR TITLE
Update colab.ipynb

### PR DESCRIPTION
**Pull request by ILoveCuteKittyCats**

### CODE REVIEW

**Review by LostRuins — COMMENTED** [review]
is there an issue with our model? What's the reason for changing it?

**Comment by ILoveCuteKittyCats** [comment]
ah no, I just thought that Mistral was more popular

**Comment by ILoveCuteKittyCats** [comment]
I changed line 73 and 74 because ggml is replaced with gguf

**Comment by LostRuins** [comment]
Hmm... I think we'll be sticking to the current set of default models featuring Tiefighter, however I will change the .ggml extension to .gguf as suggested. You can still manually edit the model input to use mistral if you prefer.

**Comment by ILoveCuteKittyCats** [comment]
ok, thanks!

**Pull request closed without merging**
